services:
  backend:
    build: ./backend
    image: YOUR_DH_USERNAME/express-flask-backend:latest
    container_name: flask-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: YOUR_DH_USERNAME/express-flask-frontend:latest
    container_name: express-frontend
    environment:
      - BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
